### PR TITLE
Update to 4.2.2

### PR DESCRIPTION
**Pull request by Geequlim**

### CODE REVIEW

**Comment by anttioja** [comment]
Thanks again, you beat me to the update every time before I come back from work xD

**Comment by anttioja** [comment]
By the way, I would like to add you to the contributors and give credit. Which name would you like me to add (Geequlim or something else?) and is it okay to put your gmail address there?

**Comment by Geequlim** [comment]
Geequlim geequlim@gmail.com, thanks!

**Comment by anttioja** [comment]
Done now from 4.2.0 through 4.2.2. Thanks again :)

**Pull request merged**
