### PR TITLE
Update to 4.2.1

### PR DESCRIPTION
**Pull request by Geequlim**

### CODE REVIEW

**Comment by anttioja** [comment]
Thanks for your contribution. I was going to update this today after work :)

**Comment by anttioja** [comment]
We should probably try to push this package to AUR as well. I just need to get in touch with the AUR guys.

**Comment by Geequlim** [comment]
I think so.
Please add a remote and push to it to AUR.

**Comment by Geequlim** [comment]
You can name it as `texturepacker-git` :)

**Pull request merged**
